DROP TABLE IF EXISTS GAME_PLAYER;
DROP TABLE IF EXISTS GAME;
DROP TABLE IF EXISTS PLAYER;

CREATE TABLE PLAYER (
  ID                INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  USERNAME          VARCHAR(100),
  PASSWORD          VARCHAR(100)
) ENGINE INNODB;

CREATE TABLE GAME (
  ID                INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME              VARCHAR(100) NOT NULL,
  PASSWORD          VARCHAR(100),
  VICTORY_CONDITION VARCHAR(100) NOT NULL
) ENGINE INNODB;

CREATE TABLE GAME_PLAYER (
  ID                INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PLAYER_ID         INT(10) UNSIGNED,
  GAME_ID           INT(10) UNSIGNED,
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAME (ID),
  UNIQUE KEY (PLAYER_ID, GAME_ID)
) ENGINE INNODB;

CREATE TABLE DECK (
  ID                INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  GAME_ID           INT(10) UNSIGNED NOT NULL,
  TYPE              VARCHAR(100) NOT NULL,
  CLASS_NAME        VARCHAR(100) NOT NULL,
  FOREIGN KEY (GAME_ID) REFERENCES GAME(ID)
) ENGINE INNODB;